CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user TEXT UNIQUE NOT NULL
);

CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT NOT NULL
);

CREATE TABLE labels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    image_id INTEGER,
    answer TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE masks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    image_id INTEGER,
    mask_path TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
